### PR TITLE
Use separate build and install scripts in travis

### PR DESCRIPTION
**Pull request by sbc100**
This approach has several advantages:

(1) If any step in the build fails the follow steps
are not run.  With travis the scripts are run
consecutively even if an earlier one failed.

(2) Makes it easier to run the scripts locally
outside of travis CI, for debugging.

(3) The syntax is a lot clearer.

Also, switch to container-based travis runs by
setting sudo to false. This allows for faster
startup.

Also, enable testing of the NaCl build in travis
now, since the issue that previously prevented
this has now been fixed

### CODE REVIEW

**Comment by nigels-com** [comment]
Scott, I recommend merging this.  I gave it spin, and looked it over.
https://travis-ci.org/nigels-com/regal

**Comment by sbc100** [comment]
Any update on this?

**Comment by sbc100** [comment]
Ping..

**Comment by techtonik** [comment]
Yes, I'd like to see this merged before starting work on Appveyour scripts.

**Comment by nigels-com** [comment]
Sorry for the delay.

**Comment by techtonik** [comment]
Good to know that the project is alive. https://github.com/p3/regal/pull/154 is another easy cleanup candidate.

**Pull request merged**
